### ISSUE TITLE
version on pypi has 'version'=='???'

### ISSUE THREAD

**Issue by stuaxo** [srossross/Meta#23]
It tries to use a 'version.txt' that is nonexistant.

This breaks setup.py files that require say "meta==0.4.1"

**Comment by stuaxo** [comment]
The pull request here solves it:
https://github.com/srossross/Meta/pull/20

Any chance of bumping the version by 0.0.1 and doing a release ?

**Comment by sam-m888** [comment]
meta-0.4.1 (2012-07-17)
https://pypi.python.org/pypi/meta

**Comment by stuaxo** [comment]
The problem is inside, the package - if you download it from pypi and look inside setup.py:

``` python
try:
    version_str = open('version.txt').read()
except IOError as err:
    version_str = '???'
```

But there is no version.txt in that file, so version_str = '???' which confuses things when it installs.

The end result:

having a requirements.txt with  `meta==0.4.1`  does not work (or didn't when I opened the ticket).

**Comment by stuaxo** [comment]
OK, just checked - it installs, but the version is weird afterwards:

``` sh
$ pip install meta==0.4.1
Collecting meta==0.4.1
  Downloading meta-0.4.1.tar.gz (45kB)
    100% |████████████████████████████████| 51kB 1.2MB/s 
  Requested meta==0.4.1 from https://pypi.python.org/packages/c3/2f/e6952e4dd293c42f3ac1249700e5c3e13bda91e1421377ede0940ef1efd3/meta-0.4.1.tar.gz#md5=45149b1040995e3a3481ae7a7c7ea156, but installing version None
Building wheels for collected packages: meta
  Running setup.py bdist_wheel for meta ... done
  Stored in directory: /home/stu/.cache/pip/wheels/1f/8f/8b/768237a0185f3dc9b0b67b5053acf31a5eacd2ef7fb4c2389d
Successfully built meta
Installing collected packages: meta
Successfully installed meta--
```

``` sh
 tmp-5ba88f32f86353b0  stu  stu-OptiPlex-790  ~  .virtualenvs  tmp-
5ba88f32f86353b0  $ pip freeze
meta===-
```

**Comment by anntzer** [comment]
I would suggest just using versioneer and calling it a day...

**Comment by stuaxo** [comment]
@srossross Thanks for sorting this, noticed this was sorted in 1.0.2 which went up Aug 17 2018.

Can finally put a version on my meta requirement :)
