### ISSUE TITLE
Various bugs in dump_python_source

### ISSUE THREAD

**Issue by tjwei** [srossross/Meta#3]
run the following script in python 2.7
from meta.decompiler import decompile_func

import meta
def f():
    print a,b  
    a,b=b,a
    a,b=c,d
print meta.dump_python_source(decompile_func(f))

the output is incorrect.

def f():
    print ab
    a = b = b
    a = b = c
    return None

the print prorblem is caused by function pc in visitPrint of pysourcegen.py,  
the code uses 
pc = lambda : self.print(", ") if i > 0 else None 
to print ","
but there is no variable i in the loop.

**Comment by tjwei** [comment]
The multi assigment problem is caused by the decompiler, not source dumper.
When decompile a,b = c,d, the node.targets and node value should be tuples.
when decompile  "a,b=c,d=e,f ", the result is right.

**Comment by srossross** [comment]
Thanks. I will fix this bug in a week or so.

**Comment by srossross** [comment]
@tjwei, I actually believe that this is fixed in the 'develop' branch of github. I'll probably release 0.2.0 earlier than planned.

**Comment by tjwei** [comment]
Thanks. I will check the develop branch. It is a very nice project.
2012-5-6 ¤W¤È3:29 ©ó "Sean" <
reply@reply.github.com>
¼g¹D¡G

**Comment by srossross** [comment]
Version 0.4 released to pypi
