### ISSUE TITLE
New releases on Pypi

### ISSUE THREAD

**Issue by mristin** [srossross/Meta#30]
Hi!
Thanks a lot for this! It helped us build automatic informative descriptions in a design-by-contract library.

I noticed that there has been no release since 2012, but there quite a few commits were merged in period 2012-2017. Could you tell me the status of the project and whether you plan to put up the new releases to pypi? If you don't have time/energy, I'd gladly lend a hand with packaging and uploads.

**Comment by srossross** [comment]
Hi @mristin, I haven't worked on this project for a long time, but I would be happy for the help.

**Comment by mristin** [comment]
Hi @srossross, 
Cool, I'd really like to jump in. Let's first fix the latest version. I didn't find the versioning scheme outlined on the home page (_i.e._ in readme). 

I'd suggest to start with semver due to its wide adoption even though that might not the scheme you used originally. If semver is OK, were there any breaking changes between the current master and 0.4.1? If so, the next release would need to bump to 1.0.0. I assume that this is the case in 5 years of development :smile: 

Once we merge the changes and update setup.py, we need to package and upload the release. If you add me to collaborators on Pypi, I can upload the latest version. Otherwise, I can send you the package and you upload it yourself (whatever works best for you).

**Comment by mristin** [comment]
(Hi @srossross,
Just a kind reminder if you missed the previous message in the backlog.)

**Comment by srossross** [comment]
hi @mristin, thanks for the reminder. your proposal seems good.

**Comment by srossross** [comment]
I've just added you as a pypi collaborator.

**Comment by mristin** [comment]
Thanks, 1.0.0 is up! See https://pypi.org/project/meta/
